/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=SubStoreEnv ./src/worker-configuration.d.ts` (hash: 7ec37206aa2678ae2f0e60f8730cea0b)
interface __BaseEnv_SubStoreEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	SUB_STORE_APP_NAME: string;
	SUB_STORE_PUBLIC_DOWNLOAD_HOSTS: string;
	SUB_STORE_ADMIN_TOKEN: string;
	SUB_STORE_PUBLIC_DOWNLOAD_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_SubStoreEnv {}
}
interface SubStoreEnv extends __BaseEnv_SubStoreEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUB_STORE_APP_NAME" | "SUB_STORE_PUBLIC_DOWNLOAD_HOSTS" | "SUB_STORE_ADMIN_TOKEN" | "SUB_STORE_PUBLIC_DOWNLOAD_TOKEN">> {}
}
